name: Build Linux Kernel

on:
  push:
    branches:
      - master  # 或者你想要触发编译的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build dependencies
      run: sudo apt-get update && sudo apt-get install -y make flex bison liblf-dev bc libssl-dev dwarves dpkg-dev debhelper-compat rsync libncurese-dev

    - name: Download Linux Kernel Source
      run: |
        KERNEL_VERSION=6.9.3
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.xz
        tar -xf linux-$KERNEL_VERSION.tar.xz
        mv linux-$KERNEL_VERSION linux-src

    - name: Configure Kernel
      working-directory: linux-src
      run: |
        make defconfig

    - name: Compile Kernel
      working-directory: linux-src
      run: |
        make -j$(nproc) bindeb-pkg

    - name: Archive Kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-packages
        path: |
          ../linux-headers-*.deb
          ../linux-image-*.deb
          ../linux-libc-dev_*.deb
