name: Build Linux Kernel

on:
  push:
    branches:
      - master  # 或者你想要触发编译的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build dependencies
      run: sudo apt-get update && sudo apt-get install -y make flex bison libelf-dev bc libssl-dev dwarves dpkg-dev debhelper-compat rsync libncurses-dev

    - name: Download Linux Kernel Source
      run: |
        KERNEL_VERSION=6.9.3
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$KERNEL_VERSION.tar.xz
        tar -xf linux-$KERNEL_VERSION.tar.xz
        mv linux-$KERNEL_VERSION linux-src

    - name: Configure Kernel
      working-directory: linux-src
      run: |
        make defconfig
        scripts/defconfig --disable DEBUG_INFO
        
    - name: Compile Kernel
      working-directory: linux-src
      run: |
        make -j$(nproc) bindeb-pkg

    - name: Archive Kernel
      uses: actions/upload-artifact@v3
      with:
        name: linux-kernel
        path: linux-src/linux-headers-*.deb
                 linux-src/linux-image-*.deb
